name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - run: sudo echo "\ndeb http://apt.llvm.org/focal/ llvm-toolchain-focal main\ndeb-src http://apt.llvm.org/focal/ llvm-toolchain-focal main\ndeb http://apt.llvm.org/focal/ llvm-toolchain-focal-14 main\ndeb-src http://apt.llvm.org/focal/ llvm-toolchain-focal-14 main\ndeb http://apt.llvm.org/focal/ llvm-toolchain-focal-15 main\ndeb-src http://apt.llvm.org/focal/ llvm-toolchain-focal-15 main" >> /etc/apt/sources.list
    - run: sudo apt update -y
    - run: sudo apt-get install git fakeroot build-essential libarchive-dev  libarchive-tools ncurses-dev xz-utils libssl-dev bc flex libelf-dev bison llvm libncurses-dev gawk flex bison openssl dkms libelf-dev libudev-dev libpci-dev clang lld libiberty-dev autoconf -y
    - run: git submodule update --init --recursive
    - run: make -j $(nproc) CC=clang LD=ld.lld AR=llvm-ar NM=llvm-nm STRIP=llvm-strip   OBJCOPY=llvm-objcopy OBJDUMP=llvm-objdump READELF=llvm-readelf   HOSTCC=clang HOSTCXX=clang++ HOSTAR=llvm-ar HOSTLD=ld.lld
    - run: bsdtar -cf  workflow.tar *
    - run: xz -e -9 -T $(nproc) workflow.tar
    - run: mkdir tar.dir
    - run: mv workflow.tar.xz tar.dir/
    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: workflow.tar.xz
        path: ./tar.dir/
